#
#
[minter]
# --minter-node-url
api_addr = "tcp://127.0.0.1:8843/v2/"

#
#
[cosmos]
# --cosmos-mnemonic 
# mnemonic for management wallet Minter Hub Validator owner 
mnemonic = "#COSMOS_MNEMONIC#"
# --cosmos-node-url
grpc_addr = "127.0.0.1:9090"
# --tm-node-url
rpc_addr = "127.0.0.1:36657"

#
#
[ethereum]
#
gas_price_providers = [
    "ethgasstation",
    "etherchain"
]

